# [image]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [image]    Script Date: 24.04.2023 13:59:09 ******/
CREATE DATABASE [image]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'image', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\image.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'image_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\image_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [image] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [image].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [image] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [image] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [image] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [image] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [image] SET ARITHABORT OFF 
GO
ALTER DATABASE [image] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [image] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [image] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [image] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [image] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [image] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [image] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [image] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [image] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [image] SET  DISABLE_BROKER 
GO
ALTER DATABASE [image] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [image] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [image] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [image] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [image] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [image] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [image] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [image] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [image] SET  MULTI_USER 
GO
ALTER DATABASE [image] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [image] SET DB_CHAINING OFF 
GO
ALTER DATABASE [image] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [image] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [image] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [image] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [image] SET QUERY_STORE = OFF
GO

# [dbo].[imageProduct]

In [0]:
USE [image]
GO

In [0]:
/****** Object:  Table [dbo].[imageProduct]    Script Date: 24.04.2023 13:59:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[imageProduct](
	[ProductKey] [int] IDENTITY(1,1) NOT NULL,
	[ProductName] [nvarchar](50) NULL,
	[ProductImage] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [image]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [image] SET  READ_WRITE 
GO